SELECT * FROM customer_data LIMIT 10;

-- Q) Total revenue generated by male and female customers 
SELECT gender, SUM(purchase_amount) AS revenue 
FROM customer_data GROUP BY gender;

-- Q) Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount 
FROM customer_data 
WHERE discount_applied ="Yes" 
AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_data);

-- Q) Which are the top 5 products with the highest average review rating? 
SELECT item_purchased, ROUND(AVG(review_rating),2) AS avg_product_rating 
FROM customer_data 
GROUP BY item_purchased 
ORDER BY AVG(review_rating) DESC LIMIT 5;

-- Q) Compare the average purchase amounts between EXPRESS SHIPPING and STANDARD SHIPPING
SELECT ROUND(AVG(purchase_amount),2), shipping_type 
FROM customer_data 
WHERE shipping_type IN ("Express", "Standard") 
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
 SELECT COUNT(*) AS total_customers, ROUND(AVG(purchase_amount),2), SUM(purchase_amount), subscription_status
 FROM customer_data GROUP BY subscription_status;

-- Q Which five products have the highest amounts of purchase with discount applied?
SELECT item_purchased, 
100* SUM(CASE WHEN discount_applied="yes" THEN 1 ELSE 0 END)/COUNT(*) AS percent_when_discount_applied 
FROM customer_data 
GROUP BY item_purchased 
ORDER BY percent_when_discount_applied DESC
LIMIT 5 ;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE 
WHEN previous_purchases= 1 THEN 'New'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'Loyal'
END AS customer_segment
FROM customer_data)

SELECT customer_segment, COUNT(*) AS no_of_customers FROM customer_type 
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS(
SELECT category, item_purchased, COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC ) AS item_rank
FROM customer_data
GROUP BY category, item_purchased)
SELECT item_rank, category, item_purchased, total_orders FROM item_counts WHERE item_rank<=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers 
FROM customer_data  WHERE previous_purchases>=5  
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group? 
SELECT age_group, SUM(purchase_amount), ROUND(AVG(purchase_amount),2) 
FROM customer_data 
GROUP BY age_group 
ORDER BY SUM(purchase_amount) DESC;

